import { Entity, PrimaryGeneratedColumn, Column, ManyToOne, CreateDateColumn, JoinColumn } from 'typeorm';
import { Wallet } from './wallet.entity';

export enum TransactionType {
  DEPOSIT = 'deposit',
  TRANSFER = 'transfer',
}

export enum TransactionStatus {
  PENDING = 'pending',
  SUCCESS = 'success',
  FAILED = 'failed',
}

@Entity()
export class Transaction {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  // Unique reference from Paystack or generated by us for transfers
  @Column({ unique: true })
  reference: string; 

  @Column({
    type: 'enum',
    enum: TransactionType,
  })
  type: TransactionType;

  @Column({
    type: 'enum',
    enum: TransactionStatus,
    default: TransactionStatus.PENDING
  })
  status: TransactionStatus;

  @Column('decimal', { precision: 12, scale: 2 })
  amount: number;

  // FEES: Optional, but good practice. We will keep it 0 for now.
  @Column('decimal', { precision: 12, scale: 2, default: 0 })
  fee: number;

  @CreateDateColumn()
  created_at: Date;

  // RELATIONS
  
  // Who sent the money? (Nullable because a Deposit has no internal sender)
  @ManyToOne(() => Wallet, { nullable: true }) 
  @JoinColumn({ name: 'sender_wallet_id' })
  sender_wallet: Wallet;

  // Who received the money?
  @ManyToOne(() => Wallet, { nullable: true }) 
  @JoinColumn({ name: 'receiver_wallet_id' })
  receiver_wallet: Wallet;
}